MVC/Areas/Admin/Controllers/DeparmentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OmSaiModels.Admin;
using OmSaiServices.Admin.Implementations;

namespace GeneralTemplate.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DeparmentController : Controller
    {
        private readonly DepartmentService _departmentService;
        public DeparmentController()
        {
            _departmentService = new DepartmentService();

        }

        //public IActionResult Index()
        //{

        //    return View(_departmentService.GetAll());
        //}


        public ActionResult Index()
        {
            var allData = _departmentService.GetAll();

            return View(allData);
        }

        public IActionResult Create()
        {
            DepartmentModel s = new DepartmentModel();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DepartmentModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Record added successfully!";
                    _departmentService.Create(model);
                }
                else
                {
                    var errorMessages = new List<string>();
                    foreach (var state in ModelState)
                    {
                        foreach (var error in state.Value.Errors)
                        {
                            errorMessages.Add(error.ErrorMessage);
                        }
                    }
                    TempData["errors"] = errorMessages;
                }

                return RedirectToAction(nameof(Index));// nameof checks method compiletime to avoid errors
                                                       //return RedirectToAction(nameof(Index), model);    // If we pass data, it will append to url as a query string

            }
            catch
            {
                TempData["error"] = "Something went wrong!";
                return View("Index", model);
            }
        }



       
        //[HttpPost]
        //public IActionResult Create(DepartmentModel d)
        //{
        //    DepartmentModel s = new DepartmentModel();
        //    _departmentService.Create(d);

        //    return RedirectToAction("Index");
        //}

        public IActionResult Edit(int id)
        {
            DepartmentModel s =_departmentService.GetById(id);
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Record updated successfully!";
                    _departmentService.Update(model);
                }
                else
                {
                    var errorMessages = new List<string>();
                    foreach (var state in ModelState)
                    {
                        foreach (var error in state.Value.Errors)
                        {
                            errorMessages.Add(error.ErrorMessage);
                        }
                    }
                    TempData["errors"] = errorMessages;
                }

                return RedirectToAction(nameof(Index));             // nameof checks method compiletime to avoid errors
            }
            catch
            {
                TempData["error"] = "Something went wrong!";
                return View("Index", model);
            }
        }



        //[HttpPost]
        //public IActionResult Edit(DepartmentModel d)
        //{ 
        //    _departmentService.Update(d);
        //    return RedirectToAction("Index");
        //}


        public IActionResult Delete(int id)
        {
            _departmentService.Delete(id);
            return RedirectToAction("Index");
        }





    }
}

MVC/Areas/Admin/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OmSaiModels.Admin;
using OmSaiServices.Admin.Implementations;
using OmSaiServices.Admin.Interfaces;

namespace GeneralTemplate.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DepartmentController : Controller
    {
        private readonly DepartmentService _departmentService;
        public DepartmentController()
        {
            _departmentService = new DepartmentService();

        }

        public ActionResult Index()
        {
            var allData = _departmentService.GetAll();
			ViewBag.AllData = allData;

			return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DepartmentModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Record added successfully!";
                    _departmentService.Create(model);
                }
                else
                {
                    var errorMessages = new List<string>();
                    foreach (var state in ModelState)
                    {
                        foreach (var error in state.Value.Errors)
                        {
                            errorMessages.Add(error.ErrorMessage);
                        }
                    }
                    TempData["errors"] = errorMessages;
                }

                return RedirectToAction(nameof(Index));// nameof checks method compiletime to avoid errors
                                                       //return RedirectToAction(nameof(Index), model);    // If we pass data, it will append to url as a query string

            }
            catch
            {
                TempData["error"] = "Something went wrong!";
                return View("Index", model);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["success"] = "Record updated successfully!";
                    _departmentService.Update(model);
                }
                else
                {
                    var errorMessages = new List<string>();
                    foreach (var state in ModelState)
                    {
                        foreach (var error in state.Value.Errors)
                        {
                            errorMessages.Add(error.ErrorMessage);
                        }
                    }
                    TempData["errors"] = errorMessages;
                }

                return RedirectToAction(nameof(Index));             // nameof checks method compiletime to avoid errors
            }
            catch
            {
                TempData["error"] = "Something went wrong!";
                return View("Index", model);
            }
        }



        //[HttpPost]
        //public IActionResult Edit(DepartmentModel d)
        //{ 
        //    _departmentService.Update(d);
        //    return RedirectToAction("Index");
        //}


		public IActionResult Delete(int id)
		{
			_departmentService.Delete(id);
			return RedirectToAction("Index");
		}




	}
}

MVC/Areas/Admin/Views/Department/Create.cshtml
@* @model OmSaiModels.Admin.DepartmentModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using(Html.BeginForm()){
    <table>
        
        <tr>
            <td>Department Name</td>
            <td>@Html.TextBoxFor(e => e.DepartmentName)</td>
        </tr>

        <tr>
            <td>Status</td>
            <td>@Html.TextBoxFor(e => e.Status)</td>
        </tr>

        <tr>
            <td><input type="submit" value="Submit"/></td>
        </tr>


    </table>
}

 *@




@{
    ViewData["Title"] = "Create Department";
}

<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">
                    Add New Department
                </h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Master</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Deparment" asp-action="Index">Roles</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Create
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->


<div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
        <partial name="~/Views/shared/_alertpartial.cshtml" />
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class=" mb-4">
                    <div class="card">
                        <div class="card-body">
                            <form asp-action="Create" method="post">

                                <div class="form-group mb-3">
                                    <label for="departmentName">Department Name</label>
                                    <input type="text" name="departmentName" id="departmentName" class="form-control" />
                                </div>

                                <div class="form-group mb-3 form-check form-switch ">
                                    <label id="Status">Status</label>
                                    <input class="form-check-input" type="checkbox" id="Status" name="status" />
                                </div>

                                <button type="submit" class="btn btn-outline-primary">Create</button>
                                <a class="btn btn-outline-warning" asp-area="Admin" asp-controller="Deparment" asp-action="Index"> Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MVC/Areas/Admin/Views/Department/Edit.cshtml
@* @model OmSaiModels.Admin.DepartmentModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <table>

        <tr>
            <td>Department Id</td>
            <td>@Html.TextBoxFor(e => e.DepartmentId)</td>
        </tr>
        <tr>
            <td>Department Name</td>
            <td>@Html.TextBoxFor(e => e.DepartmentName)</td>
        </tr>

        <tr>
            <td>Status</td>
            <td>@Html.TextBoxFor(e => e.Status)</td>
        </tr>

        <tr>
            <td><input type="submit" value="Update" /></td>
        </tr>


    </table>
} *@



@using Microsoft.AspNetCore.Identity
 @using Microsoft.AspNetCore.Identity.Data;
@model OmSaiModels.Admin.DepartmentModel

<h1>Edit Department</h1>

<div asp-validation-summary="All" class="text-danger"></div>

<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">
                    Edit Department
                </h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Master</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Deparment" asp-action="Index">Roles</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Edit
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->


<div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
        <partial name="~/Views/shared/_alertpartial.cshtml" />
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class=" mb-4">
                    <div class="card">
                        <div class="card-body">
                            <form asp-action="Edit" asp-controller="Deparment" asp-area="Admin" method="post">
                                <input type="hidden" asp-for="DepartmentId" />
                                <div class="form-group mb-3">
                                    <label asp-for="DepartmentName"></label>
                                    <input asp-for="DepartmentName" class="form-control" />
                                </div>
                               @*  <div class="form-group mb-3">
                                    <label asp-for="Status"></label>
                                    <input type="radio" asp-for="Status" value="true" name="status"/> true
                                    <input type="radio" asp-for="Status" value="false" name="status" />false
                                </div> *@


                                <div class="form-group mb-3 form-check form-switch ">
                                    <label asp-for="Status"></label>
                                    <input class="form-check-input" type="checkbox" asp-for="Status" name="status"   />
                                </div>

                               @*  <div class="form-group mb-3">
                                    <label asp-for="Status"></label>
                                    <input type="radio" asp-for="Status" value="true" id="statusTrue" /> True
                                    <input type="radio" asp-for="Status" value="false" id="statusFalse" /> False
                                </div> *@



                                <span asp-validation-for="DepartmentName" class="text-danger"></span>
                                <span asp-validation-for="Status" class="text-danger"></span>
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a class="btn btn-outline-warning" asp-area="Admin" asp-controller="Deparment" asp-action="Index"> Cancel</a>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MVC/Areas/Admin/Views/Department/Index - Copy.cshtml
@* @model IEnumerable<OmSaiModels.Admin.DepartmentModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
     
<table class="table-bordered">
    <thead>
    <tr>
        <th>Deparment Id</th>
        <th>Deparment Name</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>@item.DepartmentId</td>
                <td>@item.DepartmentName</td>
                <td>@item.Status</td>
                <td>
                    @Html.ActionLink("Edit","Edit",new {@id=item.DepartmentId})
                    @Html.ActionLink("Delete","Delete",new {@id=item.DepartmentId})


                   
                </td>
            </tr>
        }
    </tbody>


</table>

 *@



 @using Microsoft.AspNetCore.Identity.Data;
@model IEnumerable<OmSaiModels.Admin.DepartmentModel>

@{
    ViewData["Title"] = "Deparments";
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["AreaName"] = "Admin";
    ViewData["ControllerName"] = "Deparment";
    int serialNumber = 0;
}

@section css {
    <style>
        .btnEdit:hover {
            cursor: pointer;
        }
    </style>
}


<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">
                    Departments
                    <a asp-area="Admin" asp-controller="Deparment" asp-action="Create" class="btn btn-sm btn-primary">Add New</a>
                </h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Master</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Departments
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->


<div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
        <partial name="~/Views/shared/_alertpartial.cshtml" />
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12" id="leftCard">
                <div class=" mb-4">

                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>Department Name</th>
                                <th>Status</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                serialNumber++;
                                <tr class="align-middle">
                                    <td>@serialNumber</td>
                                    <td>@item.DepartmentName</td>
                                    <td>@item.Status</td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.DepartmentId" class="btn btn-warning">Edit</a>
                                        <a asp-action="Delete" asp-route-id="@item.DepartmentId" class="btn btn-danger">Delete</a>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>
</div>

@* <a asp-action="Create" class="btn btn-primary">Create Role</a> *@

MVC/Areas/Admin/Views/Department/Index.cshtml
@using Microsoft.AspNetCore.Identity.Data;
@model OmSaiModels.Admin.DepartmentModel

@{
    ViewData["Title"] = "Departments";
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["AreaName"] = "Admin";
    ViewData["ControllerName"] = "Department";
    int serialNumber = 0;
}

@section css {
    <style>
        .btnEdit:hover {
            cursor: pointer;
        }
    </style>
}


<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="page-title">
                    Departments
                    <button class="btn btn-sm btn-primary" id="btnShowForm">Add New</button>
                </h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Master</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Departments
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->


<div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
        <partial name="~/Views/shared/_alertpartial.cshtml" />
        <div class="row">


            <div class="col-lg-12 col-md-12 col-sm-12" id="leftCard">
                <div class="card">
                    <div class="table-responsive">
                        <table class="table card-table table-vcenter text-nowrap">
                            <thead>
                                <tr>
                                    <th class="w-1">No.</th>
                                    <th>Department Name</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.AllData)
                                {
                                    serialNumber++;
                                    <tr class="align-middle">
                                        <td>@serialNumber</td>
                                        <td>@item.DepartmentName</td>
                                        <td>
                                            @if (item.Status == true)
                                            {
                                                <span class="status-icon bg-success"></span> <span>Active</span>
                                            }
                                            else
                                            {
                                                <span class="status-icon bg-danger"></span> <span>Inactive</span>
                                            }
                                        </td>
                                        <td>
                                            <nav class="nav justify-content-center">
                                                <a class="nav-link badge shadow m-0 text-warning btn btnEdit"
                                                   data-id="@item.DepartmentId"
                                                   data-name="@item.DepartmentName"
                                                   data-status="@item.Status">
                                                    <i class="fe fe-edit"></i>
                                                </a>
                                                <a class="nav-link badge shadow m-0 text-danger btn btn-delete"
                                                   data-delete_id="@item.DepartmentId"
                                                   data-delete_display="@item.DepartmentName">
                                                    <i class="fe fe-trash"></i>
                                                </a>
                                            </nav>
                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-12" id="rightCard" style="display:none;">
                <div class="card card-warning card-outline mb-4 ">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <form id="DepartmentForm" method="post" asp-area="admin" asp-controller="Department" asp-action="Create" asp-antiforgery="true">
                        <input type="hidden" asp-for="DepartmentId" id="DepartmentId" />
                        <div class="card-body">
                            <div class="mb-3">
                                <label asp-for="DepartmentName" class="col-form-label">Department Name</label>
                                <input type="text" class="form-control" asp-for="DepartmentName" placeholder="Department Name" required>
                            </div>
                            <div class="form-check mt-2">
                                <input class="form-check-input" asp-for="Status" type="checkbox" id="status" checked>
                                <label class="form-check-label" for="status">Is Active</label>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-secondary" id="btnSubmit">Save</button>
                            <button type="button" class="btn btn-outline-warning" id="btnCloseForm">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>


        </div>
    </div>
</div>


@section modals {
    <partial name="~/Views/shared/_DeleteModelPartial.cshtml" />
}

@section Scripts {
    <script>
        $('#btnShowForm').click(() => {
            $('#leftCard').removeClass("col-lg-12 col-md-12").addClass("col-lg-8 col-md-8");
            $('#rightCard').fadeIn();
            $('#btnShowForm').fadeOut();
            $('#btnSubmit').text("Save");

            $('#DepartmentForm').attr('action', '/admin/Department/Create');
            $('#DepartmentId').val("");
        });

        $('#btnCloseForm').click(() => {
            $('#leftCard').addClass("col-lg-12 col-md-12").removeClass("col-lg-8 col-md-8");
            $('#rightCard').fadeOut();
            $('#btnShowForm').fadeIn();
        });

        $('.btnEdit').click(function () {
            $('#leftCard').removeClass("col-lg-12 col-md-12").addClass("col-lg-8 col-md-8");
            $('#rightCard').fadeIn();
            $('#btnShowForm').fadeOut();
            $('#btnSubmit').text("Update");

            let data = $(this).data();
            $('#DepartmentId').val(data.id);
            $('#DepartmentName').val(data.name);
            $('#DepartmentForm').attr('action', '/admin/Department/Edit');
        });
        $('.btn-delete').click(function () {
            $('#leftCard').removeClass("col-lg-12 col-md-12").addClass("col-lg-8 col-md-8");
            $('#rightCard').fadeIn();
            $('#btnShowForm').fadeOut();
            $('#btnSubmit').text("Delete");

            let data = $(this).data();
            $('#DepartmentId').val(data.delete_id);
            $('#DepartmentForm').attr('action', '/admin/Department/Edit');
        });
    </script>
}